### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by etamtlosz** [ChristianKuehnel/plantgateway#26]
Hi,
my plantgateway won't start, throwing the following error:
```pi@raspberrypi:~ $ plantgateway
Traceback (most recent call last):
  File "/usr/local/bin/plantgateway", line 37, in <module>
    main()
  File "/usr/local/bin/plantgateway", line 24, in main
    pg = PlantGateway()
  File "/usr/local/lib/python3.5/dist-packages/plantgw/__init__.py", line 125, in __init__
    self.config = Configuration(config_file_path)
  File "/usr/local/lib/python3.5/dist-packages/plantgw/__init__.py", line 30, in __init__
    config = yaml.load(config_file)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "/home/pi/.plantgw.yaml", line 20, column 5
could not find expected ':'
  in "/home/pi/.plantgw.yaml", line 21, column 5
```

**Comment by ChristianKuehnel** [comment]
hi @etamtlosz ,

the last line in the error message indicate the problem:
```
could not find expected ':'
  in "/home/pi/.plantgw.yaml", line 21, column 5
```

It seems that your config file does not meet the yaml syntax.

**Comment by etamtlosz** [comment]
I found it. I didn't have space after colon.
Case closed.
