### ISSUE TITLE
Running on Raspberry Pi 3

### ISSUE THREAD

**Issue by marcotini** [ChristianKuehnel/plantgateway#3]
What did I do wrong?

```
pi@raspberrypi:~ $ plantgateway 
INFO:root:loaded config file from /home/pi/.plantgw.yaml
Traceback (most recent call last):
  File "/usr/local/bin/plantgateway", line 20, in <module>
    main()
  File "/usr/local/bin/plantgateway", line 14, in main
    pg = PlantGateway()
  File "/usr/local/lib/python3.4/dist-packages/plantgw/__init__.py", line 76, in __init__
    self._start_client()
  File "/usr/local/lib/python3.4/dist-packages/plantgw/__init__.py", line 90, in _start_client
    self.mqtt_client.connect(self.config.mqtt_server, self.config.mqtt_port, 60)
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname
```

**Comment by ChristianKuehnel** [comment]
The error occurs during the connection to the MQTT server. Did you check if the address of the mqtt server is correct? Can you ping the MQTT server?

**Comment by ChristianKuehnel** [comment]
did not hear anything -> closing issue
