### ISSUE TITLE
New Raspbian Image on RPI Zero W - no route to host [solved]

### ISSUE THREAD

**Issue by RDG88** [ChristianKuehnel/plantgateway#31]
My RPI Zero W won't connect to the plant sensor. Debug logs says the following:

```
Tue, 16 Apr 2019 21:38:39 INFO     PlantGateway version 0.5.1
Tue, 16 Apr 2019 21:38:39 INFO     loaded config file from /root/.plantgw.yaml
Tue, 16 Apr 2019 21:38:39 INFO     Getting data from sensor myplant
Tue, 16 Apr 2019 21:38:39 ERROR    could not read data from C4:7C:8D:6A:94:48 (myplant) with reason: [Errno 113] No route to host
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 212, in process_all
    self.process_mac(sensor)
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 190, in process_mac
    self._publish(sensor_config, poller)
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 163, in _publish
    self.start_client()
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 137, in start_client
    self._start_client()
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 159, in _start_client
    self.mqtt_client.connect(self.config.mqtt_server, self.config.mqtt_port, 60)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
Tue, 16 Apr 2019 21:38:39 INFO     try 1 of 6: could not process sensor(s) myplant. Waiting 1 sec for next try
Tue, 16 Apr 2019 21:38:40 INFO     Getting data from sensor myplant
Tue, 16 Apr 2019 21:38:40 ERROR    could not read data from C4:7C:8D:6A:94:48 (myplant) with reason: [Errno 113] No route to host
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 212, in process_all
    self.process_mac(sensor)
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 190, in process_mac
    self._publish(sensor_config, poller)
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 163, in _publish
    self.start_client()
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 137, in start_client
    self._start_client()
  File "/usr/local/lib/python3.5/dist-packages/plantgw/plantgw.py", line 159, in _start_client
    self.mqtt_client.connect(self.config.mqtt_server, self.config.mqtt_port, 60)
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

```

Any clue what this could be?

hcitool lescan shows the mac adres:

```
pi@plant-gateway:~ $ sudo hcitool lescane
LE Scan ...
00:12:6F:3D:F9:9E Beoplay S3
57:79:81:1E:7B:EF (unknown)
57:79:81:1E:7B:EF (unknown)
5B:F2:2A:EB:62:B0 (unknown)
60:63:52:59:04:32 (unknown)
70:02:FB:45:BC:CB (unknown)
70:02:FB:45:BC:CB (unknown)
00:12:6F:3D:F9:9E (unknown)
73:FD:FA:AB:B7:57 (unknown)
73:FD:FA:AB:B7:57 (unknown)
60:2D:AA:53:B2:98 (unknown)
60:2D:AA:53:B2:98 (unknown)
4B:F3:2F:0E:D4:78 (unknown)
C8:5E:32:D8:7C:2B (unknown)
C4:7C:8D:6A:94:48 (unknown)
C4:7C:8D:6A:94:48 Flower care  <==
77:01:58:D9:B9:34 (unknown)
77:01:58:D9:B9:34 (unknown)
4B:F3:2F:0E:D4:78 (unknown)
```

With gatttool i'm able to connect but get the following log:

```
root@plant-gateway:~# /usr/bin/gatttool -b C4:7C:8D:6A:94:48 -I
[C4:7C:8D:6A:94:48][LE]> connect
Attempting to connect to C4:7C:8D:6A:94:48
Connection successful
Notification handle = 0x0021 value: 00
Notification handle = 0x0021 value: 00
Notification handle = 0x0021 value: 00
[C4:7C:8D:6A:94:48][LE]>
(gatttool:17763): GLib-WARNING **: Invalid file descriptor.

```

Any clue what this could be?
Thank you

**Comment by RDG88** [comment]
Nevermind! was a MQTT problem.. please close
