### ISSUE TITLE
__init__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by szogi** [ChristianKuehnel/plantgateway#40]
Wed, 09 Oct 2019 11:22:21 INFO     PlantGateway version 0.6.2
Wed, 09 Oct 2019 11:22:21 INFO     loaded config file from /root/.plantgw.yaml
Wed, 09 Oct 2019 11:22:21 INFO     Getting data from sensor myplant
Wed, 09 Oct 2019 11:22:21 ERROR    could not read data from 11:22:33:44:55:66 (myplant) with reason: __init__() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/plantgw/plantgw.py", line 263, in process_all
    self.process_mac(sensor)
  File "/usr/local/lib/python3.7/dist-packages/plantgw/plantgw.py", line 239, in process_mac
    poller = MiFloraPoller(sensor_config.mac, BluepyBackend)
  File "/usr/local/lib/python3.7/dist-packages/miflora/miflora_poller.py", line 37, in __init__
    self._bt_interface = BluetoothInterface(backend, adapter)
TypeError: __init__() takes 2 positional arguments but 3 were given
could not read data from 11:22:33:44:55:66 (myplant) with reason: __init__() takes 2 positional arguments but 3 were given

**Comment by szogi** [comment]
bluepy-1.3.0 btlewrap-0.0.7 miflora-0.5 paho-mqtt-1.4.0 plantgateway-0.6.2 pyyaml-5.1.2 typing-3.7.4.1

Python 3.7.3

**Comment by gonecrazy25** [comment]
I am having this exact same problem.

could not read data from C4:7C:8D:63:CA:79 (front-door-plant) with reason: __init__() takes 2 positional arguments but 3 were given

bluepy (1.3.0), btlewrap (0.0.7), miflora (0.5), paho-mqtt (1.4.0), plantgateway (0.6.2), PyYAML (5.1.2), typing (3.7.4.1)
Python 3.6.8

**Comment by ChristianKuehnel** [comment]
I can't test it right now, but I guess it was a problem in the btlewrap library. Can you try to upgrade to v0.0.8:
`pip install --upgrade btlewrap==0.0.8`

**Comment by ChristianKuehnel** [comment]
Sorry too fast. Please DOWNGRADE to version 0.0.4
```bash
pip remove btlewrap
pip install btlewrap==0.0.4
```

**Comment by mbonaccors** [comment]
I downgraded to btlewrap 0.0.4 and still getting the error when running plantgateway. Anything else I should be doing? Do I need to restart my raspberry pi?
