### ISSUE TITLE
Errors on freshly installed Raspian.

### ISSUE THREAD

**Issue by FallenLeave91** [ChristianKuehnel/plantgateway#9]
Can you see what went wrong?

```
Traceback (most recent call last):
  File "/usr/local/bin/plantgateway", line 30, in <module>
    main()
  File "/usr/local/bin/plantgateway", line 24, in main
    pg = PlantGateway()
  File "/usr/local/lib/python3.4/dist-packages/plantgw/__init__.py", line 95, in __init__
    self._start_client()
  File "/usr/local/lib/python3.4/dist-packages/plantgw/__init__.py", line 109, in _start_client
    self.mqtt_client.connect(self.config.mqtt_server, self.config.mqtt_port, 60)
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 700, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 822, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Martinvdm** [comment]
Same error, did you solve it?

**Comment by nkerboute** [comment]
Same error here

**Comment by ChristianKuehnel** [comment]
Can you try if setting a port for your mqtt server solves the issue?

Am Do., 13. Dez. 2018, 20:57 hat nkerboute <notifications@github.com>
geschrieben:
